export const CAROUSEL_CONFIG = {
  AUTOPLAY_DELAY: 4000, // 4 seconds
  DEFAULT_HEIGHT: 420,
  DEFAULT_MOBILE_HEIGHT: 280,
  DEFAULT_SLIDE_SIZE: "60%",
  DEFAULT_LOOP: true,
  DEFAULT_ALIGN: "center",
  DEFAULT_SHOW_INDICATORS: true,
};
